version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sentiment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql:ro

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - postgres
    # environment:
    #   - MONGO_URI: "mongodb://mongo:27107"
    #   - POSTGRES_URI: ""

volumes:
  mongo_data:
  postgres_data: